import { Module } from "@nestjs/common";
import {
  AuthModule,
  UserModule,
  CountryModule,
  StateModule,
  RoleModule,
  PermissionModule,
  CityModule,
  TaxModule,
  UserAddressModule,
  BrandModule,
  ContactUsModule,
  CmsModule,
  FaqModule,
  TestimonialModule,
  SocialMediaModule,
  IndustryModule,
  CategoryModule,
  GlobalSettingModule,
  NotificationModule,
  AttributeModule,
  AttributeValueModule,
  UomModule,
  ProductModule,
  WishlistModule,
  ProductRatingModule,
  WarehouseModule,
  OrderModule,
  FaqCategoryModule,
} from "./modules";
import { CartModule } from "./modules/cart/cart.module";

@Module({
  imports: [
    AuthModule,
    UserModule,
    CountryModule,
    StateModule,
    RoleModule,
    PermissionModule,
    CityModule,
    TaxModule,
    CmsModule,
    UserAddressModule,
    BrandModule,
    FaqModule,
    ContactUsModule,
    TestimonialModule,
    SocialMediaModule,
    IndustryModule,
    CategoryModule,
    GlobalSettingModule,
    NotificationModule,
    AttributeModule,
    AttributeValueModule,
    UomModule,
    ProductModule,
    WishlistModule,
    CartModule,
    ProductRatingModule,
    WarehouseModule,
    OrderModule,
    FaqCategoryModule,
  ],
})
export class AppModule {}
